mysteriumnetwork/mysterium-vpn-mobile

.gitignore, android/app/build.gradle, util_scripts/download-node
We have node artifact in Sonatype 👏🏻 https://github.com/mysteriumnetwork/docs/pull/19
=> Use Sonatype for mobile-node artifact

android/app/build.gradle, android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, package.json, src/app/adapters/proposals/tequilapi-proposals-adapter.ts, src/app/app-loader.ts, yarn.lock
Ref: https://github.com/mysteriumnetwork/node/issues/1225
=> Update myst node 0.10

android/app/src/main/java/network/mysterium/ui/MainVpnFragment.kt, fastlane/Fastfile
Check if fragment is attached to activity
=> Fix invalid state errors

android/app/build.gradle, android/build.gradle
I think it Fixes: mysteriumnetwork/node#1512
=> Update to next node version (with updated proposal fetch fixes)

android/app/src/main/java/network/mysterium/ui/SharedViewModel.kt
Fixes https://github.com/mysteriumnetwork/node/issues/1762
=> Show connection lost notification only if current state is NOT_CONNECTED

android/app/build.gradle, android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt, android/app/src/main/java/network/mysterium/service/core/NodeRepository.kt, android/app/src/main/java/network/mysterium/ui/MainVpnFragment.kt, android/app/src/main/res/values/strings.xml
=> Throw more specific connect errors when possible

android/app/build.gradle, android/app/src/main/java/network/mysterium/service/core/NodeRepository.kt, android/app/src/main/java/network/mysterium/ui/FeedbackFragment.kt, android/app/src/main/java/network/mysterium/ui/FeedbackViewModel.kt, android/app/src/main/res/layout/fragment_feedback.xml, android/app/src/main/res/menu/navigation_menu.xml, android/app/src/main/res/values/strings.xml
There is no need to have separate types like Bug, Connectivity Issue, Positive. Instead have just simple form which allows user to describe issue and optionally add email address. Also add notice that logs are sent too which will help investigate what went wrong.
=> Keep only issue type for feedback

android/app/src/main/java/network/mysterium/AppContainer.kt, android/app/src/main/java/network/mysterium/MainActivity.kt, android/app/src/main/java/network/mysterium/service/core/NodeRepository.kt, android/app/src/main/java/network/mysterium/ui/FeedbackFragment.kt, android/app/src/main/java/network/mysterium/ui/FeedbackViewModel.kt, android/app/src/main/java/network/mysterium/ui/ForceUpdateFragment.kt, android/app/src/main/java/network/mysterium/ui/Navigation.kt, android/app/src/main/java/network/mysterium/ui/SharedViewModel.kt, android/app/src/main/java/network/mysterium/ui/VersionViewModel.kt, android/app/src/main/res/layout/fragment_force_update.xml, android/app/src/main/res/layout/fragment_proposals_country_filter.xml, android/app/src/main/res/layout/proposal_filter_country_item.xml, android/app/src/main/res/navigation/nav_graph.xml, android/app/src/main/res/values/strings.xml
=> Add force update screen

android/app/src/main/java/network/mysterium/ui/ProposalsViewModel.kt
Related to the https://github.com/mysteriumnetwork/node/issues/2489
=> Remove initial price filters, only apply filters from UI

android/app/build.gradle, android/app/src/main/java/network/mysterium/proposal/ProposalsViewModel.kt
Fixes https://github.com/mysteriumnetwork/node/issues/2940
=> Update default price filter

android/app/build.gradle, android/app/src/main/java/network/mysterium/proposal/ProposalsFragment.kt, android/app/src/main/java/network/mysterium/proposal/ProposalsPriceFilterFragment.kt, android/app/src/main/java/network/mysterium/proposal/ProposalsViewModel.kt, android/app/src/main/java/network/mysterium/service/core/NodeRepository.kt, android/app/src/main/java/network/mysterium/terms/TermsFragment.kt, android/app/src/main/java/network/mysterium/ui/PriceUtils.kt, android/app/src/main/res/layout/fragment_proposals_price_filter.xml, android/app/src/main/res/values-de/strings.xml, android/app/src/main/res/values-ru/strings.xml, android/app/src/main/res/values/strings.xml
- Need to release node bindings
=> Use initial price settings from node

android/app/src/main/java/network/mysterium/wallet/WalletTopupWaitingPaymentFragment.kt
Fix copying payment address to clipboard
=> Set topup address clip to clipboard

android/app/src/main/java/updated/mysterium/vpn/di/Modules.kt, android/app/src/main/java/updated/mysterium/vpn/network/provider/usecase/UseCaseProvider.kt, android/app/src/main/java/updated/mysterium/vpn/network/usecase/LoginUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/ui/onboarding/viewpager/OnboardingViewPagerAdapter.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashViewModel.kt, android/app/src/main/res/layout/fragment_item_onboarding.xml, android/app/src/main/res/values/strings.xml
https://tracker.geniusee.tk/browse/MN-53#/
https://tracker.geniusee.tk/browse/MN-54#/
https://tracker.geniusee.tk/browse/MN-55#/
=> MN-53_54_55 - Fix bugs for MN-53, MN-54 and MN-55

android/app/src/main/res/layout/fragment_all_nodes.xml, android/app/src/main/res/values/strings.xml
https://tracker.geniusee.tk/browse/MN-56#/
=> MN-56 Titles over the list of nodes fixed

android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt, android/app/src/main/java/network/mysterium/service/core/MysteriumCoreService.kt, android/app/src/main/java/updated/mysterium/vpn/common/extensions/UiExtensions.kt, android/app/src/main/java/updated/mysterium/vpn/model/manual/connect/ConnectionStateModel.kt, android/app/src/main/java/updated/mysterium/vpn/model/manual/connect/ProposalModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashViewModel.kt
https://tracker.geniusee.tk/browse/MN-78#/
https://tracker.geniusee.tk/browse/MN-79#/
=> MN-78,79 - Fix bugs

android/app/build.gradle, android/app/src/main/java/updated/mysterium/vpn/App.kt, android/app/src/main/java/updated/mysterium/vpn/ui/menu/MenuActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashViewModel.kt
https://tracker.geniusee.tk/browse/MN-47#/
=> MN-47 Get help

android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/search/SearchViewModel.kt, android/app/src/main/res/layout/activity_menu.xml, android/app/src/main/res/layout/item_menu.xml
https://tracker.geniusee.tk/browse/MN-83#/
https://tracker.geniusee.tk/browse/MN-85#/
https://tracker.geniusee.tk/browse/MN-87#/
=> MN-83, 85, 87 - Fix bigs

android/app/src/main/java/updated/mysterium/vpn/ui/custom/view/ConnectionState.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeViewModel.kt, android/app/src/main/res/values/strings.xml
Move getExchangeRate to another coroutine because it can take some time
Make proposal rulable in activity because getting it from service can take some time and latent property can be uninitialised
Add Disconnecting state to HomeActivity - add Disconnecting string to button
Add error listener to connection
=> Fix background operations during connection

android/app/build.gradle, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt, android/app/src/main/res/values/strings.xml
Check and request VPN connection 
Updated version of fragment-ktx because OnActivityResult is deprecated and applied another approach witch require updated fragment version
=> Check and request VPN connection

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/network/mysterium/service/core/NodeRepository.kt, android/app/src/main/java/updated/mysterium/vpn/common/date/DateUtil.kt, android/app/src/main/java/updated/mysterium/vpn/di/Modules.kt, android/app/src/main/java/updated/mysterium/vpn/model/session/Session.kt, android/app/src/main/java/updated/mysterium/vpn/network/provider/usecase/UseCaseProvider.kt, android/app/src/main/java/updated/mysterium/vpn/network/usecase/StatisticUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/ui/balance/BalanceViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/menu/MenuActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/monitoring/MonitoringActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/monitoring/MonitoringViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/monitoring/SessionsAdapter.kt, android/app/src/main/res/layout/activity_monitoring.xml, android/app/src/main/res/layout/item_session.xml, android/app/src/main/res/values/strings.xml
Update version of mobile node
Add last sessions feature 
Add converting data and date
=> Get last sessions

android/app/build.gradle, android/app/src/main/java/updated/mysterium/vpn/common/data/DataUtil.kt, android/app/src/main/java/updated/mysterium/vpn/common/date/DateUtil.kt, android/app/src/main/java/updated/mysterium/vpn/network/usecase/StatisticUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/ui/monitoring/MonitoringActivity.kt, android/app/src/main/res/drawable/marker.xml, android/app/src/main/res/drawable/shape_line_chart.xml, android/app/src/main/res/drawable/shape_line_chart_transparent_form.xml, android/app/src/main/res/layout/activity_monitoring.xml, android/app/src/main/res/values/strings.xml
Filter all sessions to last seven days
Implement line chart with last sessions
Map all connection related to specific day connection to one connection on chart
=> Add line chart to monitoring

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/updated/mysterium/vpn/di/Modules.kt, android/app/src/main/java/updated/mysterium/vpn/model/terms/FullVersionTerm.kt, android/app/src/main/java/updated/mysterium/vpn/network/provider/usecase/UseCaseProvider.kt, android/app/src/main/java/updated/mysterium/vpn/network/usecase/StatisticUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/network/usecase/TermsUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/ui/custom/view/BalanceToolbar.kt, android/app/src/main/java/updated/mysterium/vpn/ui/menu/MenuActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/monitoring/MonitoringActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/onboarding/OnboardingActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/onboarding/OnboardingViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/terms/FullTermsAdapter.kt, android/app/src/main/java/updated/mysterium/vpn/ui/terms/ShortTermsAdapter.kt, android/app/src/main/java/updated/mysterium/vpn/ui/terms/TermsOfUseActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/terms/TermsOfUseViewModel.kt, android/app/src/main/res/drawable/icon_term_index.xml, android/app/src/main/res/drawable/short_terms_separator.xml, android/app/src/main/res/layout/activity_terms.xml, android/app/src/main/res/layout/item_full_term.xml, android/app/src/main/res/layout/item_short_term.xml, android/app/src/main/res/values/strings.xml
Commit 1:
Add terms mysterious dependency
Get full terms data and parse it to appropriate formate
Implement two versions of termsView behaviour - accepted and non
Add preferences to check accepted state of terms
Commit 2:
Fix bug with unparsable data from back then node is connecting
Update UI behaviour of line chart
=> Terms of Use

android/app/src/main/java/network/mysterium/connection/MainVpnFragment.kt, android/app/src/main/java/network/mysterium/ui/SharedViewModel.kt, android/app/src/main/res/values-de/strings.xml, android/app/src/main/res/values-ru/strings.xml, android/app/src/main/res/values/strings.xml
This is a part of the https://github.com/mysteriumnetwork/node/issues/3240
=> Add support of the OnHold connection state

android/app/src/main/java/network/mysterium/service/core/NodeRepository.kt, android/app/src/main/java/updated/mysterium/vpn/common/data/WalletEstimatesUtil.kt, android/app/src/main/java/updated/mysterium/vpn/di/Modules.kt, android/app/src/main/java/updated/mysterium/vpn/network/usecase/BalanceUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/ui/custom/view/TopUpItemView.kt, android/app/src/main/java/updated/mysterium/vpn/ui/custom/view/WalletItemView.kt, android/app/src/main/java/updated/mysterium/vpn/ui/top/up/amount/TopUpAmountActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/top/up/amount/TopUpAmountViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/wallet/WalletActivity.kt, android/app/src/main/res/layout/activity_wallet.xml
Add wallet estimates on Wallet screen and TopUpAmount screen
=> Add wallet equivalents

android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt, android/app/src/main/java/updated/mysterium/vpn/ui/balance/BalanceViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/report/issue/ReportIssueActivity.kt, android/app/src/main/res/drawable/icon_error_state.xml, android/app/src/main/res/drawable/shape_big_edit_text_error.xml, android/app/src/main/res/drawable/shape_edit_text_error.xml, android/app/src/main/res/layout/activity_report_issue.xml, android/app/src/main/res/layout/activity_top_up_payment.xml, android/app/src/main/res/values/strings.xml
Added error state for Report issue fields
Handled identity error
Fixed QR size 
Removed fake payment because it cause UI and behaviour bugs. Will added back when payment will in testing
=> Fix report issue error fields

android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt, android/app/src/main/java/updated/mysterium/vpn/common/data/DataUtil.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/search/SearchActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/monitoring/MonitoringActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/profile/ProfileActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/report/issue/ReportIssueActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/settings/SettingsActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/wallet/WalletActivity.kt, android/app/src/main/res/layout/activity_monitoring.xml, android/app/src/main/res/layout/activity_profile.xml, android/app/src/main/res/layout/activity_report_issue.xml, android/app/src/main/res/layout/activity_settings.xml, android/app/src/main/res/layout/activity_wallet.xml
Added back button to Report and Settings
Updated way to show back button on menu items screens
Updated search text logic
=> Fixed UI and monitorgin data chart

android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt, android/app/src/main/java/updated/mysterium/vpn/common/data/DataUtil.kt, android/app/src/main/java/updated/mysterium/vpn/model/manual/connect/ConnectionState.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/search/SearchActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/monitoring/MonitoringActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/profile/ProfileActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/report/issue/ReportIssueActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/settings/SettingsActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/wallet/WalletActivity.kt, android/app/src/main/res/layout/activity_monitoring.xml, android/app/src/main/res/layout/activity_profile.xml, android/app/src/main/res/layout/activity_report_issue.xml, android/app/src/main/res/layout/activity_settings.xml, android/app/src/main/res/layout/activity_wallet.xml, android/app/src/main/res/values/strings.xml
Show reconnecting pop up if current connection state is OnHold
Dismiss pop up if connection back to connected state
=> Connection OnHold state

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/network/mysterium/notification/PushReceiver.kt, android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt, android/app/src/main/java/network/mysterium/service/core/MysteriumCoreService.kt, android/app/src/main/java/network/mysterium/service/core/NodeRepository.kt, android/app/src/main/java/updated/mysterium/vpn/common/data/DataUtil.kt, android/app/src/main/java/updated/mysterium/vpn/model/manual/connect/ConnectionState.kt, android/app/src/main/java/updated/mysterium/vpn/network/provider/usecase/UseCaseProvider.kt, android/app/src/main/java/updated/mysterium/vpn/network/usecase/SettingsUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/ui/balance/BalanceViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/search/SearchActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/monitoring/MonitoringActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/profile/ProfileActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/report/issue/ReportIssueActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/settings/SettingsActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/settings/SettingsViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/top/up/payment/TopUpPaymentViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/wallet/WalletActivity.kt, android/app/src/main/res/layout/activity_monitoring.xml, android/app/src/main/res/layout/activity_profile.xml, android/app/src/main/res/layout/activity_report_issue.xml, android/app/src/main/res/layout/activity_settings.xml, android/app/src/main/res/layout/activity_wallet.xml, android/app/src/main/res/values/strings.xml
Added resident country previous choice
Added send request of  resident country
Cleared push history after successful payment
Updated version of mobile node
=> Added resident country back-end

android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt, android/app/src/main/java/updated/mysterium/vpn/common/data/DataUtil.kt, android/app/src/main/java/updated/mysterium/vpn/common/languages/LanguagesUtil.kt, android/app/src/main/java/updated/mysterium/vpn/database/preferences/SharedPreferencesList.kt, android/app/src/main/java/updated/mysterium/vpn/di/Modules.kt, android/app/src/main/java/updated/mysterium/vpn/network/usecase/SettingsUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/select/node/all/AllNodesViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/menu/MenuActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/menu/MenuViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/monitoring/MonitoringActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashViewModel.kt, android/app/src/main/res/values-ru/strings.xml
Added language select feature
Check user default local on starting and convert user locale language to one of able languages
=> Apply language selection

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/updated/mysterium/vpn/di/Modules.kt, android/app/src/main/java/updated/mysterium/vpn/ui/favourites/FavouritesActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/favourites/FavouritesAdapter.kt, android/app/src/main/java/updated/mysterium/vpn/ui/favourites/FavouritesViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/search/SearchActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/search/SearchViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/select/node/saved/SavedNodesFragment.kt, android/app/src/main/res/layout/activity_favourites.xml, android/app/src/main/res/values/strings.xml
Added favourites screen, old way of showing saved nodes will be deleted in future
Added cache logic to Search screen
=> Added favourites screen

android/app/src/main/java/network/mysterium/notification/Notifications.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt
=> Updated notification flow

android/app/src/main/java/network/mysterium/AppNotificationManager.kt, android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt, android/app/src/main/java/updated/mysterium/vpn/ui/base/BaseActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/base/BaseViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/home/HomeViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt
Updated way of checking internet connection by ping server
Updated way of handling back-end error
Moved service from HomeActivity
Updated notification flow after disconnecting
Added new fake payment sandbox
=> Updated way of checking internet connection

android/app/src/main/java/network/mysterium/service/core/NodeRepository.kt, android/app/src/main/java/updated/mysterium/vpn/ui/manual/connect/select/node/all/AllNodesViewModel.kt, android/app/src/main/res/layout/activity_top_up_payment.xml, android/app/src/main/res/layout/card_connected.xml, android/app/src/main/res/layout/pop_up_account_password.xml, android/app/src/main/res/layout/pop_up_download_key.xml, android/app/src/main/res/layout/pop_up_import_account.xml, android/app/src/main/res/layout/pop_up_insufficient_funds.xml, android/app/src/main/res/layout/pop_up_lost_connection.xml, android/app/src/main/res/layout/pop_up_new_version.xml, android/app/src/main/res/layout/pop_up_node_failed.xml, android/app/src/main/res/layout/pop_up_payment_canceled.xml, android/app/src/main/res/layout/pop_up_payment_expired.xml, android/app/src/main/res/layout/pop_up_payment_not_work.xml, android/app/src/main/res/layout/pop_up_payment_successfully.xml, android/app/src/main/res/layout/pop_up_referral_code.xml, android/app/src/main/res/layout/pop_up_retry_registration.xml, android/app/src/main/res/layout/pop_up_terms.xml, android/app/src/main/res/layout/pop_up_top_up_account.xml, android/app/src/main/res/layout/pop_up_wi_fi_error.xml, android/app/src/main/res/values-ru/strings.xml
Unify pop-up width
Connected screen in Russian language
Payment screen in Russian language
=> Feature/after demo UI fixes

android/app/src/main/java/network/mysterium/AppBroadcastReceiver.kt, android/app/src/main/java/network/mysterium/service/core/NodeRepository.kt, android/app/src/main/java/updated/mysterium/vpn/common/extensions/ContextExtensions.kt, android/app/src/main/java/updated/mysterium/vpn/database/preferences/SharedPreferencesList.kt, android/app/src/main/java/updated/mysterium/vpn/network/usecase/SettingsUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/ui/connection/ConnectionActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/connection/ConnectionViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/home/selection/HomeSelectionActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/settings/SettingsActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/settings/SettingsViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/wallet/WalletActivity.kt, android/app/src/main/res/drawable/shape_lighting.xml, android/app/src/main/res/layout/activity_settings.xml, android/app/src/main/res/layout/activity_top_up_crypto.xml, android/app/src/main/res/values-pt-rBR/strings.xml, android/app/src/main/res/values-ru/strings.xml, android/app/src/main/res/values-tr/strings.xml, android/app/src/main/res/values/strings.xml
Minor fixes
Added dark mode switcher
=> Apply fixes after planning

android/app/src/main/java/updated/mysterium/vpn/ui/prepare/top/up/PrepareTopUpActivity.kt, android/app/src/main/res/layout/item_short_term.xml, android/app/src/main/res/layout/pop_up_download_key.xml, android/app/src/main/res/layout/pop_up_referral_code.xml, android/app/src/main/res/values-ar/strings.xml, android/app/src/main/res/values-night/colors.xml, android/app/src/main/res/values-pt-rBR/strings.xml, android/app/src/main/res/values-ru/strings.xml, android/app/src/main/res/values-tr/strings.xml, android/app/src/main/res/values-zh-rCN/strings.xml, android/app/src/main/res/values/colors.xml, android/app/src/main/res/values/strings.xml
Added error state to referral token edit text
Removed hiding of entered text(token)
=> Updated referral token

android/app/src/main/java/updated/mysterium/vpn/network/usecase/FilterUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/ui/favourites/FavouritesActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/nodes/list/FilterActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/nodes/list/FilterViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/wallet/WalletActivity.kt
Fixed Favourites connection button
Updated way of loading proposals
Fixed navigation stack on connection
=> Updated way of loading proposals

android/app/src/main/java/updated/mysterium/vpn/ui/connection/ConnectionActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/nodes/list/FilterActivity.kt
This reverts commit bdf08feca6b977a25de158af568871e097dd5930.
=> Revert "Back to filter after canceling connection"

android/app/build.gradle
This should fix problem with reconnect
=> Update Mysterium mobile node to 0.47.0-rc6

android/app/build.gradle
This fixes panic on the stats events
=> Update Mysterium mobile node to 0.47.0-rc7

android/app/src/main/res/layout/activity_profile.xml
=> Update Profile layout

android/app/build.gradle, android/app/src/main/java/updated/mysterium/vpn/App.kt, android/app/src/main/java/updated/mysterium/vpn/common/extensions/PushyExtensions.kt, android/app/src/main/java/updated/mysterium/vpn/common/extensions/StringExtensions.kt, android/app/src/main/java/updated/mysterium/vpn/di/Modules.kt, android/app/src/main/java/updated/mysterium/vpn/network/usecase/NodesUseCase.kt, android/app/src/main/java/updated/mysterium/vpn/notification/Notifications.kt, android/app/src/main/java/updated/mysterium/vpn/notification/PushReceiver.kt, android/app/src/main/java/updated/mysterium/vpn/ui/base/AllNodesViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/favourites/FavouritesActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/home/selection/FiltersAdapter.kt, android/app/src/main/java/updated/mysterium/vpn/ui/home/selection/HomeSelectionActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/home/selection/HomeSelectionViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/nodes/list/FilterActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/nodes/list/FilterViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/search/SearchActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt, android/app/src/main/res/layout/activity_home_selection.xml
Pushy subcategories and proposals periodical request
Implement smart refreshing of nodes
Added url to pushy content
Fixes: #414 
Fixes: #413
=> Pushy topic subcategories

android/app/build.gradle, android/app/src/main/java/updated/mysterium/vpn/App.kt, android/app/src/main/java/updated/mysterium/vpn/ui/home/selection/HomeSelectionActivity.kt, android/app/src/main/res/layout/activity_home_selection.xml
Updated HomeSelection screen, remove bugfender from project
Disable ability to scroll filters list
Fixes: #401
=> Bugfix/fix 1.0.5 crashes

android/app/src/main/java/updated/mysterium/vpn/ui/base/BaseActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/top/up/amount/TopUpAmountActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/top/up/crypto/TopUpCryptoActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/top/up/payment/TopUpPaymentActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/wallet/WalletActivity.kt, android/app/src/main/res/anim/slide_in_left.xml, android/app/src/main/res/anim/slide_in_right.xml, android/app/src/main/res/anim/slide_out_left.xml, android/app/src/main/res/anim/slide_out_right.xml, android/app/src/main/res/values/styles.xml
=> Add transition animations

android/app/src/main/res/values-night/styles.xml
Added navigation to night style AppTheme
=> Apply navigation to night res style

android/app/src/main/java/updated/mysterium/vpn/ui/create/account/CreateAccountActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/monitoring/MonitoringActivity.kt, android/app/src/main/res/values/strings.xml
Updated text on Connecting screen
Added invalidation of chart after data was successfully inserted
=> Change encrypted tunnel description

android/app/src/main/res/values-ru/strings.xml
**1) Shorter translation so it would fit in the smaller screens**
Продолжительность >>> Длительность
Получено >>> Принято
Выплачено >>> Оплачено
**2) Fixed word ending to match neuter gender**
(Качество) Любой >>> (Качество) Любое
=> Improved russian translation

android/app/src/main/java/updated/mysterium/vpn/App.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt, android/build.gradle
Increase target and compile API versions to 30
Fix issues after that
=> Increase API version, fix error after that

android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashViewModel.kt, android/app/src/main/res/layout/activity_profile.xml
Mainnet correct migration from testate by additional register status check.
Fixed Profile screen UI 
Related issue: https://github.com/mysteriumnetwork/mysterium-vpn-mobile/issues/468
=> Mainnet migration

android/app/src/main/java/updated/mysterium/vpn/di/Modules.kt, android/app/src/main/java/updated/mysterium/vpn/notification/PushReceiver.kt, android/app/src/main/java/updated/mysterium/vpn/ui/base/RegistrationViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/create/account/CreateAccountActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/create/account/CreateAccountViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/prepare/top/up/PrepareTopUpActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/private/key/PrivateKeyActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/splash/SplashViewModel.kt, android/app/src/main/res/layout/activity_create_account.xml
Made RegistrationViewModel with all logic of registration account
Used this VM on Splash, Create/Import account and TopUp screens
Added loader to import account process
=> Balance check on import

android/app/src/main/java/updated/mysterium/vpn/ui/pop/up/PopUpDownloadKey.kt, android/app/src/main/res/layout/pop_up_download_key.xml, android/app/src/main/res/layout/view_item_nat_compatibility_description.xml
- Fixed settings helper description
- Fixed password hint
=> Fit text in block

android/app/src/main/java/updated/mysterium/vpn/ui/connection/ConnectionActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/connection/ConnectionViewModel.kt, android/app/src/main/java/updated/mysterium/vpn/ui/home/selection/HomeSelectionActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/nodes/list/FilterActivity.kt
- fixed node display
- removed double loading
- updated navigation
=> Fixed smart connect

android/app/src/main/res/values-ru/strings.xml, android/app/src/main/res/values/strings.xml
As per: https://github.com/mysteriumnetwork/mysterium-vpn-mobile/issues/540, quick fix might be better places for this warning
=> Add Myst ETH network warning

android/app/src/main/res/drawable/icon_close_payment_banner.xml, android/app/src/main/res/layout/activity_card_summary.xml, android/app/src/main/res/values/colors.xml
Fixed close button colors in dark theme
=> Fixed design of payment balance limit banner

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/updated/mysterium/vpn/notification/Notifications.kt, android/app/src/main/java/updated/mysterium/vpn/ui/private/key/PrivateKeyActivity.kt, android/app/src/main/res/values/strings.xml
Fixed storage permission request
=> Added storage permission rationale

android/app/src/main/java/updated/mysterium/vpn/ui/profile/ProfileActivity.kt
Updated storage permission request in Profile
=> Updated storage permission request in profile

android/app/src/main/java/updated/mysterium/vpn/ui/home/selection/HomeSelectionActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/top/up/card/summary/CardSummaryActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/top/up/coingate/payment/TopUpPaymentActivity.kt, android/app/src/main/res/layout/activity_top_up_payment.xml, android/app/src/main/res/layout/item_payment_balance_limit_banner.xml, android/app/src/main/res/layout/item_payment_processing_banner.xml, android/app/src/main/res/values-night/colors.xml, android/app/src/main/res/values/colors.xml
Updated design of balance limit banner
=> Added balance limit banner on crypto payment screen

android/app/src/crypto/java/updated/mysterium/vpn/ui/top/up/amount/usd/TopUpAmountUsdActivity.kt, android/app/src/main/java/updated/mysterium/vpn/notification/PushReceiver.kt
=> Fixed push notifications on API 31+; Fixed MYST currency

android/app/src/main/java/updated/mysterium/vpn/ui/home/selection/HomeSelectionActivity.kt, android/app/src/main/java/updated/mysterium/vpn/ui/home/selection/HomeSelectionViewModel.kt, android/app/src/main/res/values/strings.xml
=> new pop up urls and text
